### ISSUE TITLE
UNIQUENESS_EXCEPTION

### ISSUE THREAD

**Issue by alani1** [stamp-web/stamp-webservices#53]
I have started with a clean clone of the repo and a new clean database, imported the .sql script.

0. Set server and sql loggers to debug
1. login go to manage create one country Switzerland -->  success
2. create second country Austria -> UNIQUENESS_EXCEPTION
3. set all other loggers to debug
4. create second country Austria again -> UNIQUENESS_EXCEPTION

here the output on the server console:

```
Configuration did not contain a database password.
Enter database password: Server listening on port 9001, process=1048
MySQL database pool created for database named 'mysql2'
Logger "server" successful set to debug
Logger "sql" successful set to debug
{"message":"The object already exists","code":"UNIQUENESS_EXCEPTION","processed":true}
Logger "connection" successful set to debug
Logger "user-auth" successful set to debug
Logger "fieldDefinition" successful set to debug
{"message":"The object already exists","code":"UNIQUENESS_EXCEPTION","processed":true}
```

Logfiles are attached in [Logfiles.zip](https://github.com/stamp-web/stamp-webservices/files/539642/Logfiles.zip)

can you try to reproduce this? Is there a way to get an exception showing me which line / file created this exception in the server so I can investigate further? btw, I work with MariaDB 10.1.14 on windows 10 64bit

**Comment by alani1** [comment]
oh, for both countries I just entered the country name, and left the description field empty

**Comment by jadrake75** [comment]
ok, looking at your sql log I see the error

DEBUG: INSERT INTO COUNTRIES (ID,NAME,CREATESTAMP) VALUES(1,'Switzerland',CURDATE())
DEBUG: SELECT SQL_CALC_FOUND_ROWS cn.* FROM COUNTRIES AS cn WHERE cn.ID=1  LIMIT 0,1000
DEBUG: UPDATE SEQUENCE_GEN SET ID_VAL=? WHERE ID_NAME='COUNTRY_ID' Bind params: [1]
DEBUG: INSERT INTO COUNTRIES (ID,NAME,CREATESTAMP) VALUES(1,'Austria',CURDATE())
DEBUG: UPDATE SEQUENCE_GEN SET ID_VAL=? WHERE ID_NAME='COUNTRY_ID' Bind params: [1]
DEBUG: INSERT INTO COUNTRIES (ID,NAME,CREATESTAMP) VALUES(1,'Austria',CURDATE())

Notice the ID is never getting incremented.... it is always "1".  So that is the uniqueness exception being thrown.  So the question is why...

**Comment by jadrake75** [comment]
This is what I have in mine (of course this is a data dump from a running system that is a few months out of date...).  If you shutdown the system and update country_ID to say 1000 then start things what do you get?

OWNERSHIP_ID	150124
CATEGORY_ID	0
CATNUM_ID	151632
COLLECTION_ID	800
STAMP_ID	150860
ALBUM_ID	1340
COUNTRY_ID	4706
VERSION_ID	253
CATALOGUE_ID	38
PREF_ID	53
SELLER_ID	42

I noticed there password message on startup.  Are you able to put the password in the application.json file?  This file is not "servable" from the webservice

**Comment by alani1** [comment]
The problem was, that even after creating a first record the sequence_gen table was empty. Creating values for each Model with ID=0 at DB initialization fixes the issue. Please check attached PR.
